apiVersion: v1
kind: ConfigMap
metadata:
  name: kodespace-config
  labels:
    app: kodespace
data:
  app-url: "https://your-domain.com"
  log-level: "info"
  log-format: "json"
  rate-limit-window: "900000"
  rate-limit-max: "100"
  upload-max-size: "5242880"
  allowed-file-types: "image/jpeg,image/png,image/webp,image/gif"
  feature-comments: "true"
  feature-code-execution: "false"
  feature-live-collaboration: "false"